### ISSUE TITLE
Different name for module in modules' folder than in module's route

### ISSUE THREAD

**Issue by carleshf** [jdeon/dnd5e-printSheet#14]
I see the module installed as:

```
drwxr-xr-x  7 me me 4,0K jul 20 22:55 dnd5e-print-sheet
```

But on the console, it is looking for a file that will never be reachable because of package name:

```
Uncaught (in promise) Error: undefined. ENOENT: no such file or directory, open '/home/me/testing_software/foundryvtt-11/foundrydata/Data/modules/dnd5e-printSheet/template/htmlExportTemplate.html'
[No packages detected]
    at a.<anonymous> (foundry.js:7647:41)
    at a.value (socket.js:532:17)
    at a.value (socket.js:459:22)
    at L.emit (index.mjs:136:20)
    at manager.js:207:18
```

The part `[...]/modules/dnd5e-printSheet/[...]`.

I made sure to install the latest version of the module.

**Comment by jdeon** [comment]
Thanks for your issue, I remove the uppercase in the module name to declare it on foundry. I forgot some old name reference.
Just fix in commit 2af050e398d9785e7b7d7527ec0f748a3b127ea0.

I go generate a new release soon.

**Comment by jdeon** [comment]
Done

**Comment by carleshf** [comment]
Cool! Seems to be working now.

Thanks!
