### ISSUE TITLE
lag with no output

### ISSUE THREAD

**Issue by PocketMage** [jdeon/dnd5e-printSheet#16]
I'm on Foundry 11.313 and using dnd 5e 2.3.1. When I click the "Export" button, the module causes foundry to freeze momentarily. 
There is no dialog or output. It seems to be using deprecated code.
Here's the console output.

> Error: The value of CONFIG.DND5E.abilities has been changed to an object. The former value can be acccessed from .label.
> Deprecated since Version 2.2
> Backwards-compatible support will be removed in Version 2.4
>     at Object.logCompatibilityWarning (commons.js:2054:19)
>     at Object.toString (config.mjs:1912:19)
>     at Object.f [as escapeExpression] (handlebars.min.js:27:3781)
>     at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:11:17)
>     at h (handlebars.min.js:27:17870)
>     at c (handlebars.min.js:27:6899)
>     at Object.<anonymous> (handlebars.min.js:27:7289)
>     at Object.c (handlebars.min.js:27:19853)
>     at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:37:49)
>     at c (handlebars.min.js:27:15429)
>     at d (handlebars.min.js:27:15744)
>     at e (handlebars.min.js:28:22748)
>     at renderTemplate (foundry.js:7685:10)
>     at async PrintSheetHtml._renderInner (foundry.js:5915:16)
>     at async PrintSheetHtml._renderInner (foundry.js:6485:18)
>     at async PrintSheetHtml.convertdataToHtmlText (printHtml.js:23:24)
>     at async printActorSheet (print_sheet.js:37:22)
> logCompatibilityWarning @ commons.js:2065
> toString @ config.mjs:1912
> f @ handlebars.min.js:27
> eval @ VM6507:11
> h @ handlebars.min.js:27
> c @ handlebars.min.js:27
> (anonymous) @ handlebars.min.js:27
> c @ handlebars.min.js:27
> eval @ VM6515:37
> c @ handlebars.min.js:27
> d @ handlebars.min.js:27
> e @ handlebars.min.js:28
> renderTemplate @ foundry.js:7685
> await in renderTemplate (async)
> _renderInner @ foundry.js:5915
> _renderInner @ foundry.js:6485
> convertdataToHtmlText @ printHtml.js:23
> printActorSheet @ print_sheet.js:37
> (anonymous) @ print_sheet.js:20
> dispatch @ jquery.min.js:2
> y.handle @ jquery.min.js:2

**Comment by jdeon** [comment]
I didn't reproduce your error. On which version of the module are you ?
I think the error was fix some version ago. At some time I was push to change the of the id of the module from dnd5e-printSheet to dnd5e-print-sheet, you are perhaps at the old version and new one is not push to you anymore.

Can you try to to uninstall the module an reinstall it (last version is Version 2.3.2) ?

**Comment by jdeon** [comment]
Closed because there is no more reply.
