### ISSUE TITLE
[BUG] Export sheet: Abilities are called [object Object]

### ISSUE THREAD

**Issue by ZeroXNoxus** [jdeon/dnd5e-printSheet#17]
As the title reads, the ability scores of the print sheet are called [object Object]:

![image](https://github.com/jdeon/dnd5e-printSheet/assets/29397572/99a28cf8-04f3-4ded-b108-ed686f133a09)

Used game system: DnD: 5th Edition (current version)
Foundry version: V11 (current snapshot)

**Comment by jdeon** [comment]
I see some breaking change in the dnd 2.4 Patch Notes. I will investigate.

Just to be sure, are you using the latest version of the module (Release 2.3.2) ?

**Comment by ZeroXNoxus** [comment]
Yes I am! I just installed this module when looking for ways to give my players at the table their character sheets as a printed version.
I have now taken the time to write a module (or rather fix and enhance) that lets you display your sheet via smartphone, so this issue is, at least for me, not pressing.

**Comment by jdeon** [comment]
Done in version 2.4.0
