### ISSUE TITLE
TypeError dndSpellData.components

### ISSUE THREAD

**Issue by Zamuul** [jdeon/dnd5e-printSheet#22]
Im getting the following error, if i try to export anything:
![grafik](https://github.com/jdeon/dnd5e-printSheet/assets/122809560/08a4b35c-c22a-4886-be93-9d0098608161)
from
![grafik](https://github.com/jdeon/dnd5e-printSheet/assets/122809560/0ac3cc3d-2f99-4908-a0ce-a1a44c1afaef)

Do you have any idea, how i can fix this?

**Comment by jdeon** [comment]
Hello,

What is your foundry and dnd 5e versions ?

**Comment by Zamuul** [comment]
Foundry is Version 11 Build 315 and Dnd is 3.2.1

**Comment by jdeon** [comment]
Yes it seems the object dndSpellData.system.components has become dndSpellData.system.properties in the recent dnd 5e (was working on 3.1).
I will do a fix for this.

If you want a quick fix, you could add this code before the error line : 
`dndSpellData.system.components = dndSpellData.system.properties.reduce((acc,propertiy) => {
acc[propertiy] = true
return acc}
,{})`

**Comment by jdeon** [comment]
Fix done in 2.5.1
